### ISSUE TITLE
Error when calling zenoss

### ISSUE THREAD

**Issue by ThomasRasmussen** [RubyOpenSource/zenoss_client#11]
I've been testing the zenoss_client on ruby 1.9.3 (and 2.0) and I have found that there is apparently an error/bug when dealing with zenoss 4.2.4 (as we are running).

I get this error when trying to call zenoss:
```
/var/lib/gems/1.9.1/gems/zenoss_client-0.5.4/lib/zenoss/jsonapi.rb:70:in `parse_json': JSON request 'query' on 'EventsRouter' was unsuccessful (Zenoss::ZenossError)
	from /var/lib/gems/1.9.1/gems/zenoss_client-0.5.4/lib/zenoss/jsonapi.rb:53:in `json_request'
	from /var/lib/gems/1.9.1/gems/zenoss_client-0.5.4/lib/zenoss/jsonapi/events_router.rb:77:in `ev_query'
	from /var/lib/gems/1.9.1/gems/zenoss_client-0.5.4/lib/zenoss/jsonapi/events_router.rb:51:in `query_events'
	from ./zenoss-events.rb:15:in `<main>'
```
I have found that in this installation if I delete line 71 in /var/lib/gems/1.9.1/gems/zenoss_client-0.5.4/lib/zenoss/jsonapi/events_router.rb then it is working as expected. It is the define of function ev_query that looks like this in the original state
```
def ev_query(uid, opts)
        data = {
          :limit    => opts[:limit],
          :start    => opts[:start],
          :sort     => opts[:sort],
          :dir      => opts[:dir],
          :history  => opts[:history],
        }
```
But it should (possibly) be this:
```
def ev_query(uid, opts)
        data = {
          :limit    => opts[:limit],
          :start    => opts[:start],
          :sort     => opts[:sort],
          :dir      => opts[:dir],
        }
```
instead (thus not assigning the :history element in data-hash.

**Comment by skrobul** [comment]
Fixed in #12
